// Generated by CoffeeScript 1.4.0
(function() {

  exports.config = {
    paths: {
      "public": 'public'
    },
    files: {
      javascripts: {
        defaultExtension: 'js',
        joinTo: {
          'javascripts/app.js': /^app/,
          'javascripts/vendor.js': /^vendor/
        },
        order: {
          before: [
						'vendor/scripts/console-helper.js', 
						'vendor/scripts/json2.js', 
						'vendor/scripts/jquery.min.js', 
            'vendor/scripts/jquery.browser.mobile.min.js',
            'vendor/scripts/jquery.scrollTo.min.js',
            'vendor/scripts/jquery.event.mousestop.js',
            'vendor/scripts/jquery.mousewheel.js',
            'vendor/scripts/jquery.easing.min.js',
            'vendor/scripts/jquery.hammer.min.js',
            'vendor/scripts/paper.js',
            'vendor/scripts/tween.min.js',
						'vendor/scripts/underscore-min.js', 
						'vendor/scripts/backbone-min.js', 
						'vendor/scripts/backbone.marionette.min.js',
            'vendor/scripts/easeljs-0.6.1.min.js',
            'vendor/scripts/modernizr.js'

						/* Twitter Bootstrap */
						//'vendor/scripts/bootstrap/bootstrap-transition.js', 
						//'vendor/scripts/bootstrap/bootstrap-alert.js', 
						//'vendor/scripts/bootstrap/bootstrap-button.js', 
						//'vendor/scripts/bootstrap/bootstrap-carousel.js', 
						//'vendor/scripts/bootstrap/bootstrap-collapse.js', 
						//'vendor/scripts/bootstrap/bootstrap-dropdown.js', 
						//'vendor/scripts/bootstrap/bootstrap-modal.js', 
						//'vendor/scripts/bootstrap/bootstrap-tooltip.js', 
						//'vendor/scripts/bootstrap/bootstrap-popover.js', 
						//'vendor/scripts/bootstrap/bootstrap-scrollspy.js', 
						//'vendor/scripts/bootstrap/bootstrap-tab.js', 
						//'vendor/scripts/bootstrap/bootstrap-typeahed.js'
					]
        }
      },

      templates: {
        defaultExtension: 'hbs',
        joinTo: 'javascripts/app.js'
      }
    }
  };

}).call(this);
